# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20160712_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, help_text='Editable text field', null=True),
        ),
    ]
