# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20160713_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandstormUser',
            fields=[
                ('sid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('handle', models.CharField(blank=True, max_length=1024, null=True)),
                ('gender', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.SandstormUser', verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.SandstormUser', verbose_name='creator'),
        ),
    ]
