# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20160714_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_on', to='issues.SandstormUser', verbose_name='responsible'),
        ),
    ]
