# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandstormuser',
            name='sid',
            field=models.CharField(default='anon', max_length=32, primary_key=True, serialize=False),
        ),
    ]
