# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_auto_20160715_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandstormuser',
            name='image_url',
            field=models.CharField(default='foo', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.SandstormUser', verbose_name='creator'),
        ),
    ]
