# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_auto_20160715_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandstormuser',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
